# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Eztest < Formula
  desc "TUI for selecting and running Elixir tests"
  homepage "https://github.com/samrobinsonsauce/eztest"
  version "1.0.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/samrobinsonsauce/eztest/releases/download/v1.0.10/eztest_1.0.10_darwin_amd64.tar.gz"
      sha256 "6ca84e6f8f66ec2ccce0cf015bd9c35a1d74bfe141180940b6d76639b3fbee75"

      def install
        bin.install "eztest"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/samrobinsonsauce/eztest/releases/download/v1.0.10/eztest_1.0.10_darwin_arm64.tar.gz"
      sha256 "0a2959eea33a0b931afefc5aa4b018d174101c8b8099843eca9521ec39c0ba80"

      def install
        bin.install "eztest"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/samrobinsonsauce/eztest/releases/download/v1.0.10/eztest_1.0.10_linux_amd64.tar.gz"
      sha256 "9067fc60f5c70fd29e9c85408fb1d923918d788c5d1085c28e2d97df13f08d17"
      def install
        bin.install "eztest"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/samrobinsonsauce/eztest/releases/download/v1.0.10/eztest_1.0.10_linux_arm64.tar.gz"
      sha256 "a0aedfcb3c53e7757a4078df69fec025ef8f3689476c4bd25c31a3d469a47bcd"
      def install
        bin.install "eztest"
      end
    end
  end

  test do
    system "#{bin}/eztest", "--help"
  end
end
