# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Eztest < Formula
  desc "TUI for selecting and running Elixir tests"
  homepage "https://github.com/samrobinsonsauce/eztest"
  version "1.0.13"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/samrobinsonsauce/eztest/releases/download/v1.0.13/eztest_1.0.13_darwin_amd64.tar.gz"
      sha256 "aa88ee81746d64e5860bd7e2efad074fbbdc885bb896ee8a35ae536ece30a2f2"

      def install
        bin.install "eztest"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/samrobinsonsauce/eztest/releases/download/v1.0.13/eztest_1.0.13_darwin_arm64.tar.gz"
      sha256 "f95992c634a8685451685a23e3732aa60200b6e47a43cecb9974ea499024ce71"

      def install
        bin.install "eztest"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/samrobinsonsauce/eztest/releases/download/v1.0.13/eztest_1.0.13_linux_amd64.tar.gz"
      sha256 "4af521d395429074160a6fbb79aecb9bd0d294ed6a8fddf5974669dc8283a474"
      def install
        bin.install "eztest"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/samrobinsonsauce/eztest/releases/download/v1.0.13/eztest_1.0.13_linux_arm64.tar.gz"
      sha256 "4d3635f47a61e09bb93e04d4555412061b1d1376d25e8c6e84b271d434c79671"
      def install
        bin.install "eztest"
      end
    end
  end

  test do
    system "#{bin}/eztest", "--help"
  end
end
